simple update
Mari023/AE2WirelessTerminalLibrary pull request #79
Opened 2021-09-09 11:32 UTC by Domaman202

2021-09-09 14:24 UTC, Mari023 requested changes

2021-09-09 14:24 UTC, Mari023 commented on src/main/java/de/mari_023/fabric/ae2wtlib/mixin/ContainerTypeBuilderMixin.java
> +    }
I like this solution!
there is just one problem: it doesn't work, and I don't know why.
I do however have a solution to this which I think is even better which will push soon

2021-09-09 14:37 UTC, Mari023 commented on src/main/java/de/mari_023/fabric/ae2wtlib/mixin/ContainerTypeBuilderMixin.java
> +    }
also, this would probably have broken every other ae2 screen

2021-09-09 14:47 UTC, Mari023 commented on src/main/java/de/mari_023/fabric/ae2wtlib/mixin/ContainerTypeBuilderMixin.java
> +    }
(will be resolved by [#1](https://github.com/Domaman202/AE2WirelessTerminalLibrary/pull/1))

2021-09-10 12:43 UTC, Domaman202 commented on src/main/java/de/mari_023/fabric/ae2wtlib/mixin/PlayerInventoryInsertStack.java
> +            } catch (NullPointerException ignored) { // TODO: REPLACE THIS TO NULL SAFE BLOCK!
lol

2021-09-10 12:46 UTC, Domaman202 commented on src/main/java/de/mari_023/fabric/ae2wtlib/rei/RecipeTransferHandler.java
> +    public AutoTransferHandler.@NotNull Result handle(AutoTransferHandler.Context context) {
intellij idea complain.

2021-09-10 13:19 UTC, Mari023 commented on src/main/java/de/mari_023/fabric/ae2wtlib/mixin/ContainerTypeBuilderMixin.java
> +import org.spongepowered.asm.mixin.Unique;
import is now unused and can be removed

2021-09-10 13:49 UTC, Mari023 approved these changes

2021-09-11 08:53 UTC, merged